import type { AccommodationCountryDataSet } from "@/components/pages/services/accommodation/country/types";

const SHARED_BOUNDARIES = {
  title: "What we will and will not do",
  will_do_heading: "What we will do",
  wont_do_heading: "What we will not do",
  rows: [
    {
      will_do: "Provide shortlist options aligned to budget, commute, and timing",
      wont_do: "Claim we verify every listing unless confirmed",
    },
    {
      will_do: "Explain key contract points and common pitfalls",
      wont_do: "Publish supplier details or direct portal links",
    },
    {
      will_do: "Guide booking steps and move in timeline",
      wont_do: "Promise fixed prices or guaranteed availability",
    },
    {
      will_do: "Help you compare options clearly with notes",
      wont_do: "Act as the landlord or accommodation provider",
    },
  ],
};

const SHARED_FORM = (countryName: string): AccommodationCountryDataSet["form_section"] => ({
  title: "Not seeing what you need?",
  subtitle: `Get an accommodation shortlist based on your intake, city, and budget in ${countryName}.`,
  button_label: "Get My Accommodation Shortlist",
  micro_text: "Shortlist typically within 24 to 48 hours (working days).",
  disclosure:
    "Accommodation options are provided via third party housing partners. We guide you in selecting suitable options and understanding key terms; availability, pricing, and contract terms are set by the provider.",
  trust_line:
    "IAA Regulated . F202537807 . 128 City Road, London EC1V 2NX . 100+ Google Reviews",
});

export const ACCOMMODATION_COUNTRY_FULLDATA: AccommodationCountryDataSet[] = [
  // ═══════════════════════════════════════
  // UK
  // ═══════════════════════════════════════
  {
    country: "uk",
    country_name: "UK",
    secondary_image: { src: "/images/study_destinations/uk/2.jpg", alt: "Student life in the UK" },
    hero_section: {
      title: "Accommodation in the UK",
      subline:
        "Shortlists aligned to your city, intake, and budget with clear guidance and safe options.",
      support_line:
        "We guide you through third party accommodation options and help you choose what fits your commute, contract terms, and monthly budget.",
      chips: [
        { label: "London-led insights" },
        { label: "Shortlist in 24 to 48 hours" },
        { label: "Contract clarity" },
      ],
      image: { src: "/images/study_destinations/uk/1.jpg", alt: "UK student accommodation" },
    },
    quick_facts_section: {
      title: "Quick Facts",
      facts: [
        "Typical contract lengths: 40 to 51 weeks (varies by provider and city)",
        "Deposits: commonly 1 to 6 weeks rent (varies)",
        "Bills: may be included, confirm per option",
        "Booking lead time: earlier is safer for peak intakes",
        "Room types: studio, en-suite, shared (availability varies)",
      ],
      note: "Prices vary by city, room type, and intake. Figures shown are indicative ranges only.",
    },
    costs_planning_section: {
      title: "Costs and Planning",
      description: "Typical weekly cost bands for student accommodation in the UK.",
      cost_bands: [
        {
          label: "Budget",
          range: "£180 to £260/week",
          description: "Shared rooms, further from campus, bills may be extra",
        },
        {
          label: "Mid-range",
          range: "£260 to £390/week",
          description: "En-suite in purpose-built halls, closer to campus",
        },
        {
          label: "Premium",
          range: "£390+/week",
          description: "Studios, central locations, all-inclusive bills",
        },
      ],
      disclaimer:
        "Prices vary by city, room type, and intake. Final amounts are confirmed at the time of enquiry.",
    },
    choose_city_section: {
      title: "Choose your city",
      cities: [
        { name: "London" },
        { name: "Manchester" },
        { name: "Birmingham" },
        { name: "Leeds" },
        { name: "Nottingham" },
        { name: "Liverpool" },
        { name: "Bristol" },
        { name: "Sheffield" },
        { name: "Leicester" },
        { name: "Coventry" },
      ],
    },
    top_10_section: {
      title: "Top 10 student properties (UK)",
      subtitle:
        "Curated examples. Final availability and pricing depend on intake and provider terms.",
      properties: [
        {
          uniguru_label: "Modern Studio near University Quarter",
          city: "London",
          room_type: "Studio",
          price_range: "£350 to £450/week",
          contract: "44 to 51 weeks",
          available_from: "September / January",
          commute: "10 to 20 mins to key university areas",
          features: ["Bills included", "On-site gym", "24/7 security"],
        },
        {
          uniguru_label: "En-suite Room in Student Village",
          city: "Manchester",
          room_type: "En-suite",
          price_range: "£180 to £250/week",
          contract: "42 to 51 weeks",
          available_from: "September",
          commute: "10 to 15 mins to university campus",
          features: ["Bills included", "Common room", "Laundry on-site"],
        },
        {
          uniguru_label: "Shared Apartment near City Centre",
          city: "Birmingham",
          room_type: "Shared",
          price_range: "£140 to £200/week",
          contract: "44 to 51 weeks",
          available_from: "September / January",
          commute: "15 to 25 mins to university areas",
          features: ["Shared kitchen", "Wi-Fi included", "Cycle storage"],
        },
        {
          uniguru_label: "Premium Studio with City View",
          city: "London",
          room_type: "Studio",
          price_range: "£400 to £520/week",
          contract: "44 to 51 weeks",
          available_from: "September",
          commute: "5 to 15 mins to central universities",
          features: ["All-inclusive bills", "Rooftop terrace", "Study lounge"],
        },
        {
          uniguru_label: "Compact En-suite in Student Hub",
          city: "Leeds",
          room_type: "En-suite",
          price_range: "£150 to £210/week",
          contract: "42 to 51 weeks",
          available_from: "September",
          commute: "10 to 20 mins to campus",
          features: ["Bills included", "Games room", "Parcel service"],
        },
        {
          uniguru_label: "Riverside En-suite Residence",
          city: "Nottingham",
          room_type: "En-suite",
          price_range: "£155 to £220/week",
          contract: "44 to 51 weeks",
          available_from: "September / January",
          commute: "10 to 15 mins to university",
          features: ["Bills included", "On-site laundry", "Bike storage"],
        },
        {
          uniguru_label: "Budget-friendly Shared Room",
          city: "Liverpool",
          room_type: "Shared",
          price_range: "£100 to £160/week",
          contract: "42 to 51 weeks",
          available_from: "September",
          commute: "15 to 20 mins to key campuses",
          features: ["Wi-Fi included", "Common area", "Security"],
        },
        {
          uniguru_label: "Modern Apartment near Campus",
          city: "Bristol",
          room_type: "En-suite",
          price_range: "£200 to £280/week",
          contract: "44 to 51 weeks",
          available_from: "September",
          commute: "10 to 15 mins to university",
          features: ["Bills included", "Study spaces", "Gym access"],
        },
        {
          uniguru_label: "Student Studio in Quiet Area",
          city: "Sheffield",
          room_type: "Studio",
          price_range: "£170 to £240/week",
          contract: "42 to 51 weeks",
          available_from: "September / January",
          commute: "10 to 20 mins to campus",
          features: ["All-inclusive", "Kitchenette", "24/7 concierge"],
        },
        {
          uniguru_label: "Value En-suite near University",
          city: "Leicester",
          room_type: "En-suite",
          price_range: "£130 to £180/week",
          contract: "42 to 51 weeks",
          available_from: "September",
          commute: "10 to 15 mins to university campus",
          features: ["Bills included", "Common kitchen", "Laundry"],
        },
      ],
    },
    boundaries_section: SHARED_BOUNDARIES,
    form_section: SHARED_FORM("the UK"),
  },

  // ═══════════════════════════════════════
  // CANADA
  // ═══════════════════════════════════════
  {
    country: "canada",
    country_name: "Canada",
    secondary_image: { src: "/images/study_destinations/canada/2.png", alt: "Student life in Canada" },
    hero_section: {
      title: "Accommodation in Canada",
      subline:
        "Shortlists aligned to your city, intake, and budget with clear guidance and safe options.",
      support_line:
        "We guide you through third party accommodation options and help you choose what fits your commute, contract terms, and monthly budget.",
      chips: [
        { label: "London-led insights" },
        { label: "Shortlist in 24 to 48 hours" },
        { label: "Contract clarity" },
      ],
      image: { src: "/images/study_destinations/canada/1.png", alt: "Canada student accommodation" },
    },
    quick_facts_section: {
      title: "Quick Facts",
      facts: [
        "Contract lengths: varies (term and semester aligned options common)",
        "Deposits: commonly required (varies by provider)",
        "Utilities: may or may not be included, confirm per option",
        "Booking lead time: earlier is safer for September and January intakes",
        "Room types: studio, private room, shared (availability varies)",
      ],
      note: "Prices vary by city, room type, and intake. Figures shown are indicative ranges only.",
    },
    costs_planning_section: {
      title: "Costs and Planning",
      description: "Typical monthly cost bands for student accommodation in Canada.",
      cost_bands: [
        {
          label: "Budget",
          range: "CAD $700 to $1,000/month",
          description: "Shared rooms, further from downtown",
        },
        {
          label: "Mid-range",
          range: "CAD $1,000 to $1,500/month",
          description: "Private room in student housing, closer to campus",
        },
        {
          label: "Premium",
          range: "CAD $1,500+/month",
          description: "Studios, downtown locations, all-inclusive",
        },
      ],
      disclaimer:
        "Prices vary by city, room type, and intake. Final amounts are confirmed at the time of enquiry.",
    },
    choose_city_section: {
      title: "Choose your city",
      cities: [
        { name: "Toronto" },
        { name: "Vancouver" },
        { name: "Montreal" },
        { name: "Ottawa" },
        { name: "Calgary" },
        { name: "Edmonton" },
        { name: "Winnipeg" },
        { name: "Halifax" },
      ],
    },
    top_10_section: {
      title: "Top 10 student properties (Canada)",
      subtitle:
        "Curated examples. Final availability and pricing depend on intake and provider terms.",
      properties: [
        {
          uniguru_label: "Downtown Studio near University District",
          city: "Toronto",
          room_type: "Studio",
          price_range: "CAD $1,400 to $1,800/month",
          contract: "4 to 12 months",
          available_from: "September / January",
          commute: "10 to 20 mins to key campuses",
          features: ["Utilities included", "Fitness centre", "24/7 security"],
        },
        {
          uniguru_label: "Shared Apartment near Campus",
          city: "Toronto",
          room_type: "Shared",
          price_range: "CAD $800 to $1,100/month",
          contract: "4 to 12 months",
          available_from: "September",
          commute: "15 to 25 mins to university",
          features: ["Wi-Fi included", "Common lounge", "Laundry"],
        },
        {
          uniguru_label: "Modern En-suite in Student Hub",
          city: "Vancouver",
          room_type: "En-suite",
          price_range: "CAD $1,200 to $1,600/month",
          contract: "4 to 12 months",
          available_from: "September / January",
          commute: "10 to 20 mins to campus",
          features: ["Bills included", "Study rooms", "Bike storage"],
        },
        {
          uniguru_label: "Budget Room near Metro",
          city: "Montreal",
          room_type: "Private room",
          price_range: "CAD $700 to $950/month",
          contract: "4 to 12 months",
          available_from: "September",
          commute: "15 to 25 mins to university areas",
          features: ["Furnished", "Near transit", "Shared kitchen"],
        },
        {
          uniguru_label: "Private Studio in Quiet Neighbourhood",
          city: "Ottawa",
          room_type: "Studio",
          price_range: "CAD $1,000 to $1,400/month",
          contract: "4 to 12 months",
          available_from: "September / January",
          commute: "10 to 20 mins to campus",
          features: ["All-inclusive", "Kitchenette", "Parking available"],
        },
        {
          uniguru_label: "Student Residence near University",
          city: "Calgary",
          room_type: "En-suite",
          price_range: "CAD $900 to $1,200/month",
          contract: "4 to 12 months",
          available_from: "September",
          commute: "10 to 15 mins to campus",
          features: ["Utilities included", "Gym", "Common room"],
        },
        {
          uniguru_label: "Affordable Shared Living",
          city: "Edmonton",
          room_type: "Shared",
          price_range: "CAD $650 to $900/month",
          contract: "4 to 12 months",
          available_from: "September",
          commute: "15 to 25 mins to university",
          features: ["Furnished", "Wi-Fi", "Laundry on-site"],
        },
        {
          uniguru_label: "Central Room in Student House",
          city: "Winnipeg",
          room_type: "Private room",
          price_range: "CAD $600 to $850/month",
          contract: "4 to 12 months",
          available_from: "September / January",
          commute: "10 to 20 mins to campus",
          features: ["Utilities included", "Furnished", "Near transit"],
        },
        {
          uniguru_label: "Waterfront Studio Residence",
          city: "Vancouver",
          room_type: "Studio",
          price_range: "CAD $1,500 to $2,000/month",
          contract: "4 to 12 months",
          available_from: "September",
          commute: "5 to 15 mins to central campuses",
          features: ["All-inclusive", "Rooftop access", "Study lounge"],
        },
        {
          uniguru_label: "Coastal Student Housing",
          city: "Halifax",
          room_type: "En-suite",
          price_range: "CAD $800 to $1,100/month",
          contract: "4 to 12 months",
          available_from: "September",
          commute: "10 to 15 mins to university",
          features: ["Bills included", "Common area", "Security"],
        },
      ],
    },
    boundaries_section: SHARED_BOUNDARIES,
    form_section: SHARED_FORM("Canada"),
  },

  // ═══════════════════════════════════════
  // AUSTRALIA
  // ═══════════════════════════════════════
  {
    country: "australia",
    country_name: "Australia",
    secondary_image: { src: "/images/study_destinations/australia/2.jpg", alt: "Student life in Australia" },
    hero_section: {
      title: "Accommodation in Australia",
      subline:
        "Shortlists aligned to your city, intake, and budget with clear guidance and safe options.",
      support_line:
        "We guide you through third party accommodation options and help you choose what fits your commute, contract terms, and monthly budget.",
      chips: [
        { label: "London-led insights" },
        { label: "Shortlist in 24 to 48 hours" },
        { label: "Contract clarity" },
      ],
      image: { src: "/images/study_destinations/australia/1.jpg", alt: "Australia student accommodation" },
    },
    quick_facts_section: {
      title: "Quick Facts",
      facts: [
        "Contract lengths: varies (provider and city dependent)",
        "Deposits: commonly required (varies)",
        "Bills: may be included, confirm per option",
        "Booking lead time: earlier is safer for peak intakes",
        "Room types: studio, en-suite, shared (availability varies)",
      ],
      note: "Prices vary by city, room type, and intake. Figures shown are indicative ranges only.",
    },
    costs_planning_section: {
      title: "Costs and Planning",
      description: "Typical weekly cost bands for student accommodation in Australia.",
      cost_bands: [
        {
          label: "Budget",
          range: "AUD $200 to $300/week",
          description: "Shared rooms, further suburbs",
        },
        {
          label: "Mid-range",
          range: "AUD $300 to $450/week",
          description: "En-suite in student halls, near campus",
        },
        {
          label: "Premium",
          range: "AUD $450+/week",
          description: "Studios, CBD locations, all-inclusive",
        },
      ],
      disclaimer:
        "Prices vary by city, room type, and intake. Final amounts are confirmed at the time of enquiry.",
    },
    choose_city_section: {
      title: "Choose your city",
      cities: [
        { name: "Sydney" },
        { name: "Melbourne" },
        { name: "Brisbane" },
        { name: "Perth" },
        { name: "Adelaide" },
        { name: "Canberra" },
        { name: "Gold Coast" },
      ],
    },
    top_10_section: {
      title: "Top 10 student properties (Australia)",
      subtitle:
        "Curated examples. Final availability and pricing depend on intake and provider terms.",
      properties: [
        {
          uniguru_label: "CBD Studio near University Precinct",
          city: "Sydney",
          room_type: "Studio",
          price_range: "AUD $450 to $600/week",
          contract: "6 to 12 months",
          available_from: "February / July",
          commute: "10 to 20 mins to central universities",
          features: ["Bills included", "Rooftop terrace", "24/7 security"],
        },
        {
          uniguru_label: "En-suite in Student Village",
          city: "Melbourne",
          room_type: "En-suite",
          price_range: "AUD $300 to $400/week",
          contract: "6 to 12 months",
          available_from: "February / July",
          commute: "10 to 15 mins to campus",
          features: ["Bills included", "Study spaces", "Gym"],
        },
        {
          uniguru_label: "Shared Apartment near Campus",
          city: "Brisbane",
          room_type: "Shared",
          price_range: "AUD $200 to $280/week",
          contract: "6 to 12 months",
          available_from: "February",
          commute: "10 to 20 mins to university",
          features: ["Wi-Fi included", "Pool access", "Laundry"],
        },
        {
          uniguru_label: "Modern Room in Student Hub",
          city: "Perth",
          room_type: "En-suite",
          price_range: "AUD $250 to $350/week",
          contract: "6 to 12 months",
          available_from: "February / July",
          commute: "10 to 15 mins to campus",
          features: ["Utilities included", "Common lounge", "Bike storage"],
        },
        {
          uniguru_label: "Budget-friendly Shared Room",
          city: "Adelaide",
          room_type: "Shared",
          price_range: "AUD $180 to $260/week",
          contract: "6 to 12 months",
          available_from: "February",
          commute: "15 to 20 mins to university",
          features: ["Furnished", "Near transit", "Shared kitchen"],
        },
        {
          uniguru_label: "Studio Apartment near Parliament",
          city: "Canberra",
          room_type: "Studio",
          price_range: "AUD $320 to $420/week",
          contract: "6 to 12 months",
          available_from: "February / July",
          commute: "10 to 20 mins to campus",
          features: ["All-inclusive", "Study lounge", "Parking"],
        },
        {
          uniguru_label: "Coastal Student Residence",
          city: "Gold Coast",
          room_type: "En-suite",
          price_range: "AUD $250 to $350/week",
          contract: "6 to 12 months",
          available_from: "February",
          commute: "10 to 15 mins to university",
          features: ["Bills included", "Pool", "Common area"],
        },
        {
          uniguru_label: "Premium CBD Studio",
          city: "Sydney",
          room_type: "Studio",
          price_range: "AUD $550 to $720/week",
          contract: "6 to 12 months",
          available_from: "February / July",
          commute: "5 to 15 mins to central campuses",
          features: ["All-inclusive", "Concierge", "Rooftop gym"],
        },
        {
          uniguru_label: "Student House near Arts Quarter",
          city: "Melbourne",
          room_type: "Private room",
          price_range: "AUD $270 to $360/week",
          contract: "6 to 12 months",
          available_from: "February",
          commute: "10 to 20 mins to campus",
          features: ["Furnished", "Wi-Fi", "Communal garden"],
        },
        {
          uniguru_label: "Value Room near University",
          city: "Brisbane",
          room_type: "En-suite",
          price_range: "AUD $240 to $320/week",
          contract: "6 to 12 months",
          available_from: "February / July",
          commute: "10 to 15 mins to university",
          features: ["Bills included", "Laundry", "Study room"],
        },
      ],
    },
    boundaries_section: SHARED_BOUNDARIES,
    form_section: SHARED_FORM("Australia"),
  },

  // ═══════════════════════════════════════
  // NETHERLANDS
  // ═══════════════════════════════════════
  {
    country: "netherlands",
    country_name: "Netherlands",
    secondary_image: { src: "/images/study_destinations/netherlands/2.jpg", alt: "Student life in Netherlands" },
    hero_section: {
      title: "Accommodation in the Netherlands",
      subline:
        "Shortlists aligned to your city, intake, and budget with clear guidance and safe options.",
      support_line:
        "We guide you through third party accommodation options and help you choose what fits your commute, contract terms, and monthly budget.",
      chips: [
        { label: "London-led insights" },
        { label: "Shortlist in 24 to 48 hours" },
        { label: "Contract clarity" },
      ],
      image: { src: "/images/study_destinations/netherlands/1.jpg", alt: "Netherlands student accommodation" },
    },
    quick_facts_section: {
      title: "Quick Facts",
      facts: [
        "Contract lengths: varies (provider and city dependent)",
        "Deposits: commonly required (varies)",
        "Registration: you may need to register at the municipality after moving in",
        "Booking lead time: earlier is safer, housing is competitive in Dutch cities",
        "Room types: studio, private room, shared (availability varies)",
      ],
      note: "Prices vary by city, room type, and intake. Figures shown are indicative ranges only.",
    },
    costs_planning_section: {
      title: "Costs and Planning",
      description: "Typical monthly cost bands for student accommodation in the Netherlands.",
      cost_bands: [
        {
          label: "Budget",
          range: "EUR 500 to 700/month",
          description: "Shared rooms, smaller cities",
        },
        {
          label: "Mid-range",
          range: "EUR 700 to 1,000/month",
          description: "Private room in student housing, city centres",
        },
        {
          label: "Premium",
          range: "EUR 1,000+/month",
          description: "Studios, Amsterdam/Rotterdam centre, all-inclusive",
        },
      ],
      disclaimer:
        "Prices vary by city, room type, and intake. Final amounts are confirmed at the time of enquiry.",
    },
    choose_city_section: {
      title: "Choose your city",
      cities: [
        { name: "Amsterdam" },
        { name: "Rotterdam" },
        { name: "The Hague" },
        { name: "Utrecht" },
        { name: "Eindhoven" },
        { name: "Groningen" },
        { name: "Leiden" },
        { name: "Maastricht" },
      ],
    },
    top_10_section: {
      title: "Top 10 student properties (Netherlands)",
      subtitle:
        "Curated examples. Final availability and pricing depend on intake and provider terms.",
      properties: [
        {
          uniguru_label: "Canal-side Studio in City Centre",
          city: "Amsterdam",
          room_type: "Studio",
          price_range: "EUR 1,100 to 1,500/month",
          contract: "6 to 12 months",
          available_from: "September / February",
          commute: "10 to 20 mins to university",
          features: ["Bills included", "Furnished", "Bike parking"],
        },
        {
          uniguru_label: "Modern Room in Student Complex",
          city: "Rotterdam",
          room_type: "Private room",
          price_range: "EUR 650 to 900/month",
          contract: "6 to 12 months",
          available_from: "September",
          commute: "10 to 15 mins to campus",
          features: ["Wi-Fi included", "Common kitchen", "Laundry"],
        },
        {
          uniguru_label: "Shared Apartment near University",
          city: "Utrecht",
          room_type: "Shared",
          price_range: "EUR 500 to 700/month",
          contract: "6 to 12 months",
          available_from: "September / February",
          commute: "10 to 20 mins to campus",
          features: ["Furnished", "Near transit", "Communal area"],
        },
        {
          uniguru_label: "Compact Studio in Tech District",
          city: "Eindhoven",
          room_type: "Studio",
          price_range: "EUR 700 to 950/month",
          contract: "6 to 12 months",
          available_from: "September",
          commute: "10 to 15 mins to university",
          features: ["All-inclusive", "Study room", "Bike storage"],
        },
        {
          uniguru_label: "Budget Room in Student Quarter",
          city: "Groningen",
          room_type: "Private room",
          price_range: "EUR 450 to 650/month",
          contract: "6 to 12 months",
          available_from: "September / February",
          commute: "10 to 15 mins to campus",
          features: ["Furnished", "Shared kitchen", "Wi-Fi"],
        },
        {
          uniguru_label: "En-suite near Historic Centre",
          city: "Leiden",
          room_type: "En-suite",
          price_range: "EUR 650 to 900/month",
          contract: "6 to 12 months",
          available_from: "September",
          commute: "10 to 15 mins to university",
          features: ["Bills included", "Common lounge", "Laundry"],
        },
        {
          uniguru_label: "Riverside Residence",
          city: "Maastricht",
          room_type: "Private room",
          price_range: "EUR 500 to 750/month",
          contract: "6 to 12 months",
          available_from: "September / February",
          commute: "10 to 20 mins to campus",
          features: ["Furnished", "Near city centre", "Bike parking"],
        },
        {
          uniguru_label: "Premium Studio in The Hague",
          city: "The Hague",
          room_type: "Studio",
          price_range: "EUR 900 to 1,200/month",
          contract: "6 to 12 months",
          available_from: "September",
          commute: "10 to 20 mins to university",
          features: ["All-inclusive", "Furnished", "24/7 access"],
        },
        {
          uniguru_label: "Affordable Shared Living",
          city: "Amsterdam",
          room_type: "Shared",
          price_range: "EUR 600 to 850/month",
          contract: "6 to 12 months",
          available_from: "September / February",
          commute: "15 to 25 mins to campus",
          features: ["Wi-Fi", "Communal kitchen", "Central location"],
        },
        {
          uniguru_label: "Student Housing near Campus",
          city: "Rotterdam",
          room_type: "En-suite",
          price_range: "EUR 750 to 1,000/month",
          contract: "6 to 12 months",
          available_from: "September",
          commute: "5 to 15 mins to university",
          features: ["Bills included", "Study spaces", "Gym access"],
        },
      ],
    },
    boundaries_section: SHARED_BOUNDARIES,
    form_section: SHARED_FORM("the Netherlands"),
  },

  // ═══════════════════════════════════════
  // GERMANY
  // ═══════════════════════════════════════
  {
    country: "germany",
    country_name: "Germany",
    secondary_image: { src: "/images/study_destinations/germany/2.jpg", alt: "Student life in Germany" },
    hero_section: {
      title: "Accommodation in Germany",
      subline:
        "Shortlists aligned to your city, intake, and budget with clear guidance and safe options.",
      support_line:
        "We guide you through third party accommodation options and help you choose what fits your commute, contract terms, and monthly budget.",
      chips: [
        { label: "London-led insights" },
        { label: "Shortlist in 24 to 48 hours" },
        { label: "Contract clarity" },
      ],
      image: { src: "/images/study_destinations/germany/1.jpg", alt: "Germany student accommodation" },
    },
    quick_facts_section: {
      title: "Quick Facts",
      facts: [
        "Contract lengths: varies (provider and city dependent)",
        "Deposits: commonly required (Kaution, usually 2 to 3 months rent)",
        "Anmeldung: you must register your address at the local office after moving in",
        "Booking lead time: earlier is safer, especially for Munich and Berlin",
        "Room types: studio, WG (shared flat), private room (availability varies)",
      ],
      note: "Prices vary by city, room type, and intake. Figures shown are indicative ranges only.",
    },
    costs_planning_section: {
      title: "Costs and Planning",
      description: "Typical monthly cost bands for student accommodation in Germany.",
      cost_bands: [
        {
          label: "Budget",
          range: "EUR 400 to 600/month",
          description: "WG (shared flat) rooms, smaller cities",
        },
        {
          label: "Mid-range",
          range: "EUR 600 to 900/month",
          description: "Private room or small apartment, city centres",
        },
        {
          label: "Premium",
          range: "EUR 900+/month",
          description: "Studios, Munich/Berlin centre, all-inclusive",
        },
      ],
      disclaimer:
        "Prices vary by city, room type, and intake. Final amounts are confirmed at the time of enquiry.",
    },
    choose_city_section: {
      title: "Choose your city",
      cities: [
        { name: "Berlin" },
        { name: "Munich" },
        { name: "Hamburg" },
        { name: "Frankfurt" },
        { name: "Cologne" },
        { name: "Stuttgart" },
        { name: "Dusseldorf" },
        { name: "Leipzig" },
      ],
    },
    top_10_section: {
      title: "Top 10 student properties (Germany)",
      subtitle:
        "Curated examples. Final availability and pricing depend on intake and provider terms.",
      properties: [
        {
          uniguru_label: "Central Studio near University Quarter",
          city: "Berlin",
          room_type: "Studio",
          price_range: "EUR 800 to 1,100/month",
          contract: "6 to 12 months",
          available_from: "October / April",
          commute: "10 to 20 mins to university",
          features: ["Bills included", "Furnished", "24/7 access"],
        },
        {
          uniguru_label: "WG Room in Student Area",
          city: "Munich",
          room_type: "WG (shared flat)",
          price_range: "EUR 600 to 850/month",
          contract: "6 to 12 months",
          available_from: "October",
          commute: "15 to 25 mins to campus",
          features: ["Shared kitchen", "Wi-Fi", "Near U-Bahn"],
        },
        {
          uniguru_label: "Modern Apartment near Harbour",
          city: "Hamburg",
          room_type: "Private room",
          price_range: "EUR 650 to 900/month",
          contract: "6 to 12 months",
          available_from: "October / April",
          commute: "10 to 20 mins to university",
          features: ["Furnished", "Laundry", "Bike parking"],
        },
        {
          uniguru_label: "Compact Studio in Financial District",
          city: "Frankfurt",
          room_type: "Studio",
          price_range: "EUR 750 to 1,050/month",
          contract: "6 to 12 months",
          available_from: "October",
          commute: "10 to 15 mins to campus",
          features: ["All-inclusive", "Study room", "Gym access"],
        },
        {
          uniguru_label: "Budget WG near University",
          city: "Cologne",
          room_type: "WG (shared flat)",
          price_range: "EUR 450 to 650/month",
          contract: "6 to 12 months",
          available_from: "October / April",
          commute: "10 to 20 mins to campus",
          features: ["Wi-Fi included", "Shared living", "Near transit"],
        },
        {
          uniguru_label: "Student Residence near Park",
          city: "Stuttgart",
          room_type: "En-suite",
          price_range: "EUR 600 to 850/month",
          contract: "6 to 12 months",
          available_from: "October",
          commute: "10 to 15 mins to university",
          features: ["Bills included", "Common area", "Laundry"],
        },
        {
          uniguru_label: "Riverside Room in City Centre",
          city: "Dusseldorf",
          room_type: "Private room",
          price_range: "EUR 550 to 800/month",
          contract: "6 to 12 months",
          available_from: "October / April",
          commute: "10 to 20 mins to campus",
          features: ["Furnished", "Near Altstadt", "Bike storage"],
        },
        {
          uniguru_label: "Affordable Studio in East",
          city: "Leipzig",
          room_type: "Studio",
          price_range: "EUR 400 to 600/month",
          contract: "6 to 12 months",
          available_from: "October",
          commute: "10 to 15 mins to university",
          features: ["All-inclusive", "Furnished", "Quiet area"],
        },
        {
          uniguru_label: "Premium Studio in Schwabing",
          city: "Munich",
          room_type: "Studio",
          price_range: "EUR 1,000 to 1,400/month",
          contract: "6 to 12 months",
          available_from: "October / April",
          commute: "5 to 15 mins to central campuses",
          features: ["All-inclusive", "Modern kitchen", "Concierge"],
        },
        {
          uniguru_label: "Value Room in Kreuzberg",
          city: "Berlin",
          room_type: "WG (shared flat)",
          price_range: "EUR 500 to 700/month",
          contract: "6 to 12 months",
          available_from: "October",
          commute: "10 to 20 mins to university",
          features: ["Wi-Fi", "Communal living", "Near U-Bahn"],
        },
      ],
    },
    boundaries_section: SHARED_BOUNDARIES,
    form_section: SHARED_FORM("Germany"),
  },
];
